### PR TITLE
fix on config files

### PR DESCRIPTION
**Pull request by davidetome**
Regarding :

- https://github.com/robotology/community/discussions/500
- https://github.com/robotology/community/discussions/498

this PR aims to fix some config files problems (thanks to @ale-git) and have to be tested.

Once tested you'll have to tune the position PIDs on the real setup.

⚠️ REMEMBER TO FLASH `2FOC` BOARD W/ THIS [FIRMWARE](https://github.com/robotology/icub-firmware-build/blob/master/CAN/2foc/2foc.r1.dc.hex) TO DRIVE A DC MOTOR!

cc @plinioMoreno  @wevmacedo  @pattacini

### CODE REVIEW

**Comment by pattacini** [comment]
Actually, the idea was that you try out the fork we provided instead of changing your files (there are conflicts now).

@davidetome @ale-git, @wevmacedo has reported problems.
Logs available in the discussions linked above.

**Comment by plinioMoreno** [comment]
> 
> 
> Actually, the idea was that you try out the fork we provided instead of changing your files (there are conflicts now).
> 
> @davidetome @ale-git, @wevmacedo has reported problems.
> Logs available in the discussions linked above.

Sorry for the confusion on this. When I checked the PR there were files that did not have changes. So to see easier the changes, I decided to check the changed lines from this PR and commit them. Next time I will ask for changes on the PR to merge it.

**Comment by pattacini** [comment]
> Sorry for the confusion on this. When I checked the PR there were files that did not have changes. So to see easier the changes, I decided to check the changed lines from this PR and commit them. Next time I will ask for changes on the PR to merge it.

Never mind @plinioMoreno 👍🏻 

Ok clear! You can always tick in the option `hide whitespace changes` in the PR/files dashboard. Have a glance at the [result](https://github.com/vislab-tecnico-lisboa/eth-boards-setups/pull/12/files?diff=split&w=1) 🔍

⚠ @davidetome we should always check that we push meaningful changes only, hence no restyle of the formatting.

**Comment by plinioMoreno** [comment]
Thanks for the info @pattacini, so the idea now is to continue the changes and updates here.

**Comment by pattacini** [comment]
@plinioMoreno so I think you can merge the PR anyway now as the changes have been already applied.

Once the PR is merged and/or the changes have been applied, this place becomes less useful for the conversation as we will no longer able to leverage on the diffs.

Therefore, my recommendation is to open up an issue in this repo where to kick off the interaction again.
(don't forget to mention the people involved here to get their attention)

**Pull request merged**
